name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: '187.127.153.92'
          username: 'root'
          key: ${{ secrets.RAPOWER28 }}
          port: 22
          script: |
            cd /var/www/rapower28
            git config --global --add safe.directory /var/www/rapower28
            git pull --rebase origin main
